refactor: update the experience API.
logto-io/rfcs pull request #11
Opened 2024-07-09 08:17 UTC by simeng-li

## Summary

Update the experience API rfcs with the latest design.  This PR includes the following updates:

### Introduce new root-level interaction event API.

1. `POST /experience`: The new API that initiates an interaction, any existing interaction storage will be cleared. Thus users can always use this endpoint to start over during the interaction flow.
2. `PUT /experience/interaction-event`. The API to switch current interaction between `register` and `sign-in`.

### Rename the social and enterprise SSO endpoint 

- Align the endpoint suffix with our current code base by replacing `authorization-url` with `authroization-uri`.
- Align the endpoint suffix with other verification types by replacing `authenticate` with `verify`

### Introduce new profile API post /profile/password

A valid new password verification record is required to insert a new password into the user profile. So an exclusive profile endpoint for the password is required.

2024-07-10 07:11 UTC, wangsijie approved these changes, later dismissed

2024-07-10 07:11 UTC, wangsijie commented on draft/0004-experience-api.md
> +  - A existing verified email/phone verification record can be used to directly sign-in to the user account by changing the interaction event from `Register` to `SignIn`.
```suggestion
  - An existing verified email/phone verification record can be used to directly sign-in to the user account by changing the interaction event from `Register` to `SignIn`.
```

2024-08-03 15:10 UTC, gao-sun requested changes
can you double check if this update matches our latest design?

2024-08-03 15:10 UTC, gao-sun commented on draft/0004-experience-api.md
any specific reason for the trailing dots?

<img width="626" alt="image" src="https://github.com/user-attachments/assets/b36721e2-91c8-42fd-b984-54e6960acf78">

<img width="451" alt="image" src="https://github.com/user-attachments/assets/f910e9d0-69c4-44bb-ac64-7dab8138744c">

and no need for "the" in the title as it can be omitted for a shorter length and pretty print

2024-08-21 02:04 UTC, simeng-li commented on draft/0004-experience-api.md
updated

2024-08-21 07:04 UTC, wangsijie submitted a review, later dismissed

2024-08-22 04:04 UTC, gao-sun submitted a review, later dismissed

2024-08-22 07:00 UTC, charIeszhao commented
L273: uses cases -> use cases

2024-08-22 07:03 UTC, charIeszhao commented on draft/0004-experience-api.md
> +### 19. Forgot password with email
Should be 18?

2024-08-22 07:07 UTC, charIeszhao commented on draft/0004-experience-api.md
> +  | verificationId | string  | The verification record id for the MFA | Yes      |
The description should both have `period` marks.

2024-08-22 07:20 UTC, xiaoyijun approved these changes, later dismissed
Overall LGTM

2024-08-22 07:20 UTC, xiaoyijun commented on draft/0004-experience-api.md
> +  | verificationId | string                 | The verification record id                 | NO       |
```suggestion
  | Field          | Type                   | Description                                | Required |
  | -------------- | ---------------------- | ------------------------------------------ | -------- |
  | data           | Record<string, string> | Callback data from the social/SSO provider | Yes     |
  | verificationId | string                 | The verification record id                 | No       |
```

2024-08-22 07:20 UTC, xiaoyijun commented on draft/0004-experience-api.md
> +| verificationId     | string  | The verification record id that can be used to identify the user.                                                                                   | NO       |
```suggestion
| verificationId     | string  | The verification record id that can be used to identify the user.                                                                                   | No       |
```

2024-08-22 07:20 UTC, xiaoyijun commented on draft/0004-experience-api.md
> +  | verificationId | string | The verification record id for the profile data. | false    |
```suggestion
  | type           | union  | The profile data type to update.                 | Yes     |
  | value          | string | The profile data value to update.                | No    |
  | verificationId | string | The verification record id for the profile data. | No    |
```

2024-08-22 07:52 UTC, darcyYe commented on draft/0004-experience-api.md
> +  | data           | Record<string, string> | Callback data from the social/SSO provider | true     |
In other tables, we use Yes/No to indicate whether a field is required. Should align them

2024-08-22 07:52 UTC, darcyYe commented on draft/0004-experience-api.md
> +| verificationId     | string  | The verification record id that can be used to identify the user.                                                                                   | NO       |
`No` instead of `NO`?

2024-08-22 07:52 UTC, darcyYe commented on draft/0004-experience-api.md
> +  | verificationId | string                 | The verification record id                 | NO       |
`No` instead of `NO`?

2024-08-22 07:52 UTC, darcyYe commented on draft/0004-experience-api.md
> +  | type           | MFAType | The MFA type to update in the profile. | No       |
not sure whether the type should be `MfaType`, please double check

2024-08-22 08:58 UTC, simeng-li commented on draft/0004-experience-api.md
> +| verificationId     | string  | The verification record id that can be used to identify the user.                                                                                   | NO       |
Aligned to NO

2024-08-22 08:58 UTC, simeng-li commented on draft/0004-experience-api.md
> +  | verificationId | string                 | The verification record id                 | NO       |
Aligned to NO

2024-08-22 09:06 UTC, xiaoyijun approved these changes
LGTM

2024-08-22 09:39 UTC, charIeszhao approved these changes

2024-08-23 00:49 UTC, wangsijie approved these changes

2024-08-23 03:02 UTC, merged